### ISSUE TITLE
ROS not found, add_environment breaks

### ISSUE THREAD

**Issue by DariusPietschatConbotics** [fzi-forschungszentrum-informatik/robot_folders#38]
Hey! 
First of all, thanks for publishing this tool!

**Issue:**
The `add_environment` command breaks with output:
```
Execution of module 'add' failed. Error message:
'list index out of range'
```
when adding a catkin and/or colcon workspace.

**Reason:**
No necessary ROS installation can be found at the default location `/opt/ros`

**Workaround:**
Add a symlink to the actual ROS installation path.

**Background:**
I've ROS installed inside a virtual environment using [Robostack](https://robostack.github.io/index.html)

**Comment by fmauch** [comment]
Thank you for the report and good to hear from you. I'm glad that you keep using robot_folders at your new place :-)

Good that the symlink works as a workaround for you for now, I'll add a fix asap.
