### ISSUE TITLE
Add argument to provide colcon build arguments

### ISSUE THREAD

**Issue by fmauch** [fzi-forschungszentrum-informatik/robot_folders#5]
It would be very handy to be able to provide colcon arguments like `--packages-select <pkg_name>` to `fzirob make colcon`. That could be wrapped into alias commands to make such everyday tasks easily accessible in a sourced environment.

**Comment by taDachs** [comment]
I would interested in this issue

**Comment by fmauch** [comment]
Do you mean, you would like to implement this?

**Comment by fmauch** [comment]
Happy to assign you :-)

**Comment by fmauch** [comment]
Closed by #27
